In [287]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [288]:
df = pd.read_csv('/movies_metadata.csv')

In [289]:
df.head()

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0

In [290]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45466 entries, 0 to 45465
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   adult                  45466 non-null  object
 1   belongs_to_collection  4494 non-null   object
 2   budget                 45466 non-null  object
 3   genres                 45466 non-null  object
 4   homepage               7782 non-null   object
 5   id                     45466 non-null  object
 6   imdb_id                45449 non-null  object
 7   original_language      45455 non-null  object
 8   original_title         45466 non-null  object
 9   overview               44512 non-null  object
 10  popularity             45461 non-null  object
 11  poster_path            45080 non-null  object
 12  production_companies   45463 non-null  object
 13  production_countries   45463 non-null  object
 14  release_date           45379 non-null  object
 15  revenue                45460 non-null  float64
 16  runtime                45203 non-null  float64
 17  spoken_languages       45460 non-null  object
 18  status                 45379 non-null  object
 19  tagline                20412 non-null  object
 20  title                  45460 non-null  object
 21  video                  45460 non-null  object
 22  vote_average           45460 non-null  float64
 23  vote_count             45460 non-null  float64
dtypes: float64(4), object(20)
memory usage: 8.3+ MB

In [291]:
df.columns

Index(['adult', 'belongs_to_collection', 'budget', 'genres', 'homepage', 'id',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'video',
       'vote_average', 'vote_count'],
      dtype='object')

In [292]:
df.shape

(45466, 24)

In [293]:
df.isnull().sum()

adult                        0
belongs_to_collection    40972
budget                       0
genres                       0
homepage                 37684
id                           0
imdb_id                     17
original_language           11
original_title               0
overview                   954
popularity                   5
poster_path                386
production_companies         3
production_countries         3
release_date                87
revenue                      6
runtime                    263
spoken_languages             6
status                      87
tagline                  25054
title                        6
video                        6
vote_average                 6
vote_count                   6
dtype: int64

In [294]:
df.shape

(45466, 24)

# Data Cleaning

## Removing the duplicate rows

In [295]:
df.duplicated().sum()

np.int64(13)

In [296]:
df = df.drop_duplicates().reset_index(drop=True)

In [297]:
df.duplicated().sum()

np.int64(0)

## Dropping the columns which won't help in recommendation

In [298]:
columns_to_drop = ['adult', 'belongs_to_collection', 'budget', 'homepage', 'id',
       'imdb_id', 'original_title','original_language', 'poster_path', 'production_companies',
       'production_countries','release_date','revenue','spoken_languages','status', 'video', 'vote_count']
df = df.drop(columns=columns_to_drop)
display(df.columns)

Index(['genres', 'overview', 'popularity', 'runtime', 'tagline', 'title',
       'vote_average'],
      dtype='object')

In [299]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45453 entries, 0 to 45452
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   genres        45453 non-null  object
 1   overview      44499 non-null  object
 2   popularity    45448 non-null  object
 3   runtime       45190 non-null  float64
 4   tagline       20408 non-null  object
 5   title         45447 non-null  object
 6   vote_average  45447 non-null  float64
dtypes: float64(2), object(5)
memory usage: 2.4+ MB

In [300]:
df= df[['title','overview','genres','tagline','vote_average','runtime', 'popularity']]

In [301]:
df.isnull().sum()

title               6
overview          954
genres              0
tagline         25045
vote_average        6
runtime           263
popularity          5
dtype: int64

## Removing the rows having null values for title, because without the title what would the system recommend

In [302]:
df = df.dropna(subset=['title'])

In [303]:
df.shape

(45447, 7)

## For overview, filling the empty space in place of null values

In [304]:
df['overview'] = df['overview'].fillna(' ')

## Extracting the genres from column "genres"

In [305]:
df.iloc[0]['genres']

"[{'id': 16, 'name': 'Animation'}, {'id': 35, 'name': 'Comedy'}, {'id': 10751, 'name': 'Family'}]"

In [306]:
import ast

df['genres'] = df['genres'].apply(lambda x: ' '.join([genre['name'] for genre in ast.literal_eval(x)]))
display(df.head())

,title,overview,genres,tagline,vote_average,runtime,popularity
0,Toy Story,"Led by Woody, Andy's toys live happily in his ...",Animation Comedy Family,NaN,7.7,81.0,21.946943
1,Jumanji,When siblings Judy and Peter discover an encha...,Adventure Fantasy Family,Roll the dice and unleash the excitement!,6.9,104.0,17.015539
2,Grumpier Old Men,A family wedding reignites the ancient feud be...,Romance Comedy,Still Yelling. Still Fighting. Still Ready for...,6.5,101.0,11.7129
3,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",Comedy Drama Romance,Friends are the people who let you be yourself...,6.1,127.0,3.859495
4,Father of the Bride Part II,Just when George Banks has recovered from his ...,Comedy,Just When His World Is Back To Normal... He's ...,5.7,106.0,8.387519

## Filling the null values of tagline with empty space

In [307]:
df['tagline'] = df['tagline'].fillna(' ')

In [308]:
median_runtime = df['runtime'].median()
print(f"Median runtime: {median_runtime}")

df['runtime'] = df['runtime'].fillna(median_runtime)

Median runtime: 95.0

In [309]:
display(df.isnull().sum())

title           0
overview        0
genres          0
tagline         0
vote_average    0
runtime         0
popularity      0
dtype: int64

## Combining 'overview', 'genres','tagline' in a single column

So that instead of processing multiple text columns individually, we can directly apply NLP technique(TF-IDF) to a single column

In [310]:
df['tags'] = df['overview']+ ' ' + df['genres'] + ' ' + df['tagline']

In [311]:
df.head()

,title,overview,genres,tagline,vote_average,runtime,popularity,tags
0,Toy Story,"Led by Woody, Andy's toys live happily in his ...",Animation Comedy Family,,7.7,81.0,21.946943,"Led by Woody, Andy's toys live happily in his ..."
1,Jumanji,When siblings Judy and Peter discover an encha...,Adventure Fantasy Family,Roll the dice and unleash the excitement!,6.9,104.0,17.015539,When siblings Judy and Peter discover an encha...
2,Grumpier Old Men,A family wedding reignites the ancient feud be...,Romance Comedy,Still Yelling. Still Fighting. Still Ready for...,6.5,101.0,11.7129,A family wedding reignites the ancient feud be...
3,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",Comedy Drama Romance,Friends are the people who let you be yourself...,6.1,127.0,3.859495,"Cheated on, mistreated and stepped on, the wom..."
4,Father of the Bride Part II,Just when George Banks has recovered from his ...,Comedy,Just When His World Is Back To Normal... He's ...,5.7,106.0,8.387519,Just when George Banks has recovered from his ...

In [312]:
df['tags'][1]

"When siblings Judy and Peter discover an enchanted board game that opens the door to a magical world, they unwittingly invite Alan -- an adult who's been trapped inside the game for 26 years -- into their living room. Alan's only hope for freedom is to finish the game, which proves risky as all three find themselves running from giant rhinoceroses, evil monkeys and other terrifying creatures. Adventure Fantasy Family Roll the dice and unleash the excitement!"

# Natural Language Processing

In [313]:
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
import re

In [314]:
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [315]:
stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

In [316]:
def preprocess_text(text):
  text = str(text).lower()  #lowercase
  text = re.sub(r'[^a-zA-Z\s]', '', text)  #remove non-alphanumeric/punctuations

  words = text.split()  # tokenization
  words = [word for word in words if word not in stop_words]  #remove stopwords
  words = [lemmatizer.lemmatize(word) for word in words]  #lemmatization/Basic form

  return ' '.join(words)

In [317]:
df['tags'] = df['tags'].apply(preprocess_text)

In [318]:
df['tags'][1]

'sibling judy peter discover enchanted board game open door magical world unwittingly invite alan adult who trapped inside game year living room alans hope freedom finish game prof risky three find running giant rhinoceros evil monkey terrifying creature adventure fantasy family roll dice unleash excitement'

## Converting 'tags' to numerical verctor using TF-IDF

In [319]:
# To handle the missing index, it reset the index
df = df.reset_index(drop = True)

In [320]:
indices = pd.Series(df.index, index=df['title'])
indices

title
Toy Story                          0
Jumanji                            1
Grumpier Old Men                   2
Waiting to Exhale                  3
Father of the Bride Part II        4
                               ...
Subdue                         45442
Century of Birthing            45443
Betrayal                       45444
Satan Triumphant               45445
Queerama                       45446
Length: 45447, dtype: int64

In [321]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [322]:
tfidf = TfidfVectorizer(max_features= 50000, ngram_range=(1,2))

In [323]:
tfidf_matrix = tfidf.fit_transform(df['tags'])

In [324]:
tfidf_matrix

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 1715557 stored elements and shape (45447, 50000)>

## The Actual Prediction- Cosine Similarity

In [325]:
from sklearn.metrics.pairwise import cosine_similarity

In [328]:
def recommend(title, n = 10):
  if title not in indices:
    return "Movie Not Found!"

  idx = indices[title]  # to get the index of the input movie

  # to get the similarity scores & flatten() is to get the score in 1D
  sim_scores = cosine_similarity(tfidf_matrix[idx], tfidf_matrix).flatten()
  # argsort() will return the sorted index of top 10 movies
  # which are then arranged in assending order
  similar_idx = sim_scores.argsort()[::-1][1:n+1]

  # retrieving the top 10 similar movies based on indexes
  return df['title'].iloc[similar_idx]

In [329]:
recommend('Toy Story')

2996                Toy Story 2
15344               Toy Story 3
24512                 Small Fry
28972           Superstar Goofy
6434     What's Up, Tiger Lily?
17184                 Group Sex
11396    For Your Consideration
1071      Rebel Without a Cause
10937                  The Wild
1931                  Condorman
Name: title, dtype: object

In [335]:
import pickle

In [336]:
import pickle

pickle.dump(tfidf_matrix,open('tfidf_matrix.pkl','wb'))
pickle.dump(indices,open('indices.pkl','wb'))
df.to_pickle('df.pkl')
pickle.dump(tfidf,open('tfidf.pkl','wb'))